"""add house field to addresses

Revision ID: 01d21488bab7
Revises: 4217f3381a5d
Create Date: 2026-04-30 14:59:26.876430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d21488bab7'
down_revision: Union[str, Sequence[str], None] = '4217f3381a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('house', sa.String(length=20), nullable=False))
    op.add_column('addresses', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'comment')
    op.drop_column('addresses', 'house')
    # ### end Alembic commands ###
