"""add unique constraint to product name

Revision ID: fb6d5a23bd78
Revises: a47f64773f13
Create Date: 2026-05-04 19:02:40.689927

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fb6d5a23bd78"
down_revision: Union[str, Sequence[str], None] = "a47f64773f13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_products_name", "products", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_products_name", "products", type_="unique")
    # ### end Alembic commands ###
